### PR TITLE
Added deadlines introduction paragraph

### PR DESCRIPTION
**Pull request by annaliese-stone**
## Description

Added deadlines introduction paragraph.

### Type of Change

- [ ] Feature
- [ ] Bug fix
- [X ] Documentation

## Contributors

- @annaliese-stone 

## Reminder

All GitHub Actions checks must be in a passing state in this branch or fork before this pull request can be merged.

### CODE REVIEW

**Review by solisa986 — CHANGES_REQUESTED** [review]
It seems that this PR has the same changes as your 'attendance introduction paragraph' pull request. It is not necessary to have 2 open PR's with the same information. Please delete this PR. Thank you for your work!

**Review by laurennevill — APPROVED** [review]
I think this looks great!

**Comment by mariakimheinert** [comment]
As @solisa986 mentioned, it seems that both the `Deadlines-Intro` and `Attendance-Intro` branches contain the introductory paragraphs for both sections. @annaliese-stone, could you delete one PR and one of these branches to make it clear which branch you want to be reviewed?

**Comment by tuduun** [comment]
I agree with Prof Maria

**Pull request closed without merging**
